### ISSUE TITLE
how to catch contact\collided?

### ISSUE THREAD

**Issue by sg3des** [luxengine/tornago#18]
How to get event of colliding objects? 
I use this code how example - https://github.com/hydroflame/lux_dev_env/blob/master/main_dev.go

**Comment by hydroflame** [comment]
well, the simple boring answer is, you cant :( tornago is still a baby and these features are not implemented yet. I'm currently upgrading `glm/geo` with all sort of intersection tests and these will slowly get integrated in tornago to give a more feature complete physic simulation (and callbacks are planned)

**Comment by hydroflame** [comment]
now in master
